---
title: "PCA"
output: html_notebook
---

```{r libraries, echo = FALSE}
library(tidyverse)
library(ggrepel)
library(fs)
library(RcppCNPy)
```

```{r data_org, echo = FALSE}
metadata <- read_csv("data/herring_metadata.csv", 
                     show_col_types = FALSE)
### ALL SAMPLES aligned to alewife genome###
C <- as.matrix(read.table("data/post_bcf/YU_APseudo_rhallsamps.pcangsd.output.cov"))
NMFS_DNA_ID <- read_lines("data/post_bcf/samples.txt")
e <- eigen(C)
t <- tibble(PC1 = e$vectors[,1], 
            PC2 = e$vectors[,2], 
            PC3 = e$vectors[,3], 
            PC4 = e$vectors[,4])
temp <- add_column(t, NMFS_DNA_ID)
all_data <- left_join(temp, 
                      metadata, 
                      by = c("NMFS_DNA_ID" = "NMFS_DNA_ID"))

all_vars <- e$values/sum(e$values) * 100
```

```{r data_vis, echo = FALSE}
wn_colors <- c(
  # Southern Atlantic
  `Altamaha River` = "dodgerblue2", 
  `Lake Hartwell` = "#E31A1C",
  `Lake Yonah` = "green4", 
  # Mid-Atlantic
  `Roanoke River` = "#6a3d94", 
  `Choptank River` = "#ff7f00", 
  `Hudson River` = "gold1", 
  `Black Creek` = "skyblue2",
  # Connecticut Lakes
  `Quonnipaug Lake` = "#fb9a99", 
  `Rogers Lake` = "palegreen2", 
  `Pattagansett Lake` = "#CAB2D6", 
  # Canada - Northern New England
  `Saco River` = "#FDBF6F", 
  `East Grand Lake` = "khaki2", 
  `Petitcodiac River` = "maroon", 
  `Miramichi River` = "orchid1", 
  `Lake Champlain` = "deeppink1", 
  # Finger Lakes
  `Otisco Lake` = "blue1", 
  `Cayuga Lake` = "steelblue4", 
  `Seneca Lake` = "darkturquoise", 
  `Canandaigua Lake` = "green1",
  # Great Lakes
  `Lake Ontario` = "yellow4", 
  `Lake Michigan` = "yellow3", 
  `Lake Superior` = "darkorange4")

sp_shapes <- c(`aestivalis` = 22, 
               `pseudoharengus` = 24, 
               `hybrid` = 23)
```

```{r all_samples, echo = FALSE}
all_plot <- ggplot(data = all_data,
                   mapping = aes(x = PC1, 
                                 y = PC2,
                                 shape = SPECIES,
                                 fill = WATER_NAME)) +
  geom_point(size = 3) + 
  geom_point(stroke = 0.05,
             alpha = 0.75,
             size = 3.5) +
  scale_fill_manual(values = wn_colors) +
  scale_shape_manual(values = sp_shapes) +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(override.aes = list(shape = 22, 
                                                 stroke = 0.05, 
                                                 size = 3)), 
         shape = guide_legend(override.aes = list(stroke = 0.05, 
                                                  size = 3))) +
  labs(shape = "Species", 
       fill = "Water Name", 
       x = paste0("PC1 (",round(all_vars[1], 2),"%)"),
       y = paste0("PC2 (",round(all_vars[2], 2),"%)")) +
  geom_text_repel(mapping = aes(label = NMFS_DNA_ID), 
                  max.overlaps = 25)
all_plot
```

```{r}
ale_plot <- ggplot(data = filter(all_data, 
                                 SPECIES != "aestivalis"),
                   mapping = aes(x = PC1, 
                                 y = PC2,
                                 shape = SPECIES,
                                 fill = WATER_NAME)) +
  geom_point(size = 3) + 
  geom_point(stroke = 0.05,
             alpha = 0.75,
             size = 3.5) +
  scale_fill_manual(values = wn_colors) +
  scale_shape_manual(values = sp_shapes) +
  theme_bw() +
  theme(panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(override.aes = list(shape = 22, 
                                                 stroke = 0.05, 
                                                 size = 3)), 
         shape = guide_legend(override.aes = list(stroke = 0.05, 
                                                  size = 3))) +
  labs(shape = "Species", 
       fill = "Water Name", 
       x = paste0("PC1 (",round(all_vars[1], 2),"%)"),
       y = paste0("PC2 (",round(all_vars[2], 2),"%)")) +
  geom_text_repel(mapping = aes(label = NMFS_DNA_ID), 
                  max.overlaps = 25)
ale_plot
```

